CREATE TABLE links (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name varchar(255),
  link varchar(255),
  description text,
  added boolean,
  tags text
);

CREATE TABLE tags (
  id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  tag varchar(100),
  link_id bigint REFERENCES links (id)
);
INSERT INTO links (name, link, description) VALUES
('название ресурса', 'ссылка', 'описание'),
('CanIUse', 'https://caniuse.com/', 'своевременно обновляющиеся таблицы совместимости веб-технологий с браузерами'),
('Lodash', 'https://lodash.com', 'современная js-библиотека'),
('MDN', 'https://developer.mozilla.org/ru/', 'документация к веб-технологиям'),
('CSS Ruler', 'https://katydecorah.com/css-ruler/', 'наглядное сравнение единиц измерения в CSS.'),
('Шпаргалка Emmet', 'https://dwstroy.ru/stail/plaginy-rasshireniya/emmet-shpargalka/', 'исчерпывающий список сокращений Emmet.'),
('Дока', 'https://doka.guide/', 'документация к веб-технологиям на понятном языке.'),
('Способы организации CSS-кода', 'https://habr.com/ru/articles/256109/', 'подробная статья о способах организации CSS-кода на русском языке'),
('HTMLHint', 'https://htmlhint.com/', 'анализатор HTML-кода'),
('Современный учебник JavaScript', 'https://learn.javascript.ru', 'веб-учебник по JavaScript'),
('ColorScheme.ru', 'https://colorscheme.ru/', 'подбор цветов и генерация цветовых схем'),
('Google Fonts', 'https://fonts.google.com/', 'библиотека бесплатных шрифтов Google'),
('Learn X in Y Minutes', 'https://learnxinyminutes.com', 'удобная шпаргалка по всем популярным языкам'),
('html color codes', 'https://htmlcolorcodes.com/', 'наиболее полный сайт про цвет в вебе'),
('CodePen', 'https://codepen.io/', 'среда разработки для небольших веб-проектов и сообщество.'),
('Sassmeister', 'https://www.sassmeister.com/', 'песочница для Sass. Позволяет мгновенно увидеть результат преобразования Sass в CSS.'),
('Big-O Cheat Sheet', 'https://www.bigocheatsheet.com/', 'шпаргалка по алгаритмической сложности.'),
('Runebook.dev', 'https://runebook.dev/ru/', 'переводы документации на русский язык.'),
('Visualize code', 'https://pythontutor.com/visualize.html#mode=edit', 'построчная и рекурсивная визуализация исполнения кода на Python, JavaScript, C, C++ и Java.'),
('nodejs-package', 'https://github.com/hexlet-boilerplates/nodejs-package', 'эталонный npm-пакет от Hexlet.'),
('Продуманная оптимизация', 'https://optimization.guide/', 'серия статей про умную оптимизацию кода'),
('Codewars', 'https://www.codewars.com', 'платформа с большим архивом упражнений по различным языкам программирования.'),
('Codebattle', 'https://codebattle.hexlet.io', 'кодинг на скорость с реальным оппонентом или ботом'),
('Список тестовых заданий для прокачки', 'https://github.com/Hexlet/ru-test-assignments', 'тестовые задания для самостоятельного выполнения от разных it компаний'),
('LeetCode', 'https://leetcode.com/', 'продвинутые упражнения для практики'),
('SMACSS', 'https://smacss.com/', 'документация к стилю организации CSS-кода.'),
('CodeSandbox', 'https://codesandbox.io', 'онлайн-песочница и редактор для мобильных устройств под JS и его родственников. Уже подключённые фреймворки и небольшие заранее подготовленные проекты для практики'),
('Kevin Powell', 'https://www.youtube.com/@KevinPowell', 'YouTube-блог о веб-разработке на английском'),
('JavaScript.ru', 'https://www.youtube.com/c/JavaScriptru-videos', 'YouTube-канал, посвящённый JS, на русском языке. Есть несколько прейлистов про git'),
('Alek OS', 'https://www.youtube.com/@AlekOS/videos', 'YouTube-канал о жизни, обучении и программировании.'),
('Habr', 'https://habr.com/ru/all/', 'одно из крупшейших сообществ, посвящённых разработке'),
('Stack Overflow', 'https://stackoverflow.com', 'вопрос/ответ по теме разработки.'),
('git', 'https://git-scm.com', 'документация git.'),
('Code Basics', 'https://code-basics.com/ru', 'базовые бесплатные курсы по различным языкам. Сайт с открытым исходным кодом, в разработке которого можно поучаствовать'),
('Tproger', 'https://tproger.ru/', 'журнал о разработке'),
('php', 'https://www.php.net/', 'официальная документация php.'),
('Блог Хекслета', 'https://ru.hexlet.io/blog', 'полезные статьи на широкий круг тем, связанных с программированием (от ортимизации кода до жизни программиста)'),
('escape-goat', 'https://github.com/sindresorhus/escape-goat', 'библиотека для экранирования и деэкранирования HTML в JS-коде'),
('Code.mu', 'https://code.mu/ru/', 'веб-учебник по программированию'),
('jQuery', 'https://jquery.com/', 'старейшая js-библиотека для работы в вебе.'),
('CoffeeScript', 'https://coffeescript.org/', 'официальная документация CoffeeScript.'),
('explainshell.com', 'https://explainshell.com/', 'подробный мануал к командам shell.'),
('Ulbi TV', 'https://www.youtube.com/@UlbiTV', 'видео о веб-разработке и курсы.'),
('w3school', 'https://www.w3schools.com/', 'туториалы на широкий спектр тем, курсы, хостинг, упражнения и многое другое'),
('SvgPathEditor', 'https://yqnn.github.io/svg-path-editor/', 'создание и импорт svg без кода'),
('app-ideas', 'https://github.com/florinpop17/app-ideas', 'коллекция идей для пет-проектов, разделённая на уровни сложности'),
('Omatsuri', 'https://omatsuri.app', 'коллекция из 12 полезных инструментов для веб-разработки'),
('haikei', 'https://haikei.app', 'генератор svg-форм/фонов'),
('CSS Generators', 'https://css-generators.com', 'набор инструментов для создания CSS-сниппетов'),
('CSS Pattern', 'https://css-pattern.com/', '145 CSS-паттернов для фонов, созданных с помощью градиента'),
('CSS Loaders', 'https://css-loaders.com/', 'коллекция CSS-прелоадеров.'),
('CSS Tip', 'https://css-tip.com/', 'каждый день новый CSS-трюк.'),
('CSS Articles', 'https://css-articles.com/', 'авторские статьи про CSS.'),
('CSS Challenges', 'https://css-challenges.com/', 'сборник упражнений по CSS.'),
('CSS Shape', 'https://css-shape.com/', 'коллекция форм на чистом CSS.'),
('Icones', 'https://icones.js.org/', 'каталог svg-иконок'),
('Airbnb JavaScript Style Guide', 'https://github.com/airbnb/javascript', 'общепринятые стандарты js-кода'),
('transform', 'https://transform.tools/json-to-mysql', 'конвертация кода'),
('zaLinux.ru/php', 'https://zalinux.ru/?cat=114', 'статьи про php'),
('zaLinux.ru/python', 'https://zalinux.ru/?cat=86', 'статьи про python'),
('zaLinux.ru/ruby', 'https://zalinux.ru/?cat=148', 'статьи про ruby'),
('zaLinux.ru/безопасность', 'https://zalinux.ru/?cat=21', 'статьи по безопасности.'),
('zaLinux.ru/веб', 'https://zalinux.ru/?cat=156', 'статьи про веб.'),
('zaLinux.ru/сервер', 'https://zalinux.ru/?cat=115', 'статьи про серверную часть.'),
('zaLinux.ru/vim', 'https://zalinux.ru/?p=239', 'шпаргалка по vim'),
('zaLinux.ru/железо', 'https://zalinux.ru/?cat=24', 'статьи про аппаратную часть.'),
('All Sorts of Sorts', 'https://sortingalgos.miraheze.org/wiki/All_Sorts_of_Sorts', 'шпаргалка по сортировкам.'),
('Sorting Wiki', 'https://sortingalgos.miraheze.org/wiki/Main_Page', 'вики про алгоритмы сортировки.'),
('Бесплатные хостинги для веб-разработчиков', 'https://habr.com/ru/articles/535168/', 'список бесплатных хостингов (и в комментариях тоже).'),
('ECMAScript', 'https://tc39.es/ecma262/', 'последняя спецификация ECMAScript'),
('Рассказы о множествах', 'https://old.mccme.ru//free-books//vilenkin-rasomn.pdf', 'теория множеств популярным языком'),
('Color Designer', 'https://colordesigner.io/', 'сайт про цветовые решения.'),
('Шпаргалка по шаблонам проектирования', 'https://habr.com/ru/articles/210288/', 'краткие описания 23х шаблонов проектирования.'),
('Пузырьковая сортировка и все-все-все', 'https://habr.com/ru/articles/204600/', 'статья про пузырьковую сортировку и её модификации.'),
('pairwiseTool', 'https://pairwise.teremokgames.com/', 'инструмент для попарного тестирования.'),
('extended.flow', 'https://extflow.com/Algorithms', 'коллекция алгоритмических сниппетов на разных языках.'),
('Алгоритмы сортировки и их производительность', 'https://habr.com/ru/articles/689738/', 'описания алгоритмов сортировки, примеры и производительность.'),
('Описание алгоритмов сортировки и сравнение их производительности', 'https://habr.com/ru/articles/335920/', 'статья про алгоритмы сортировки.'),
('БЭМ', 'https://ru.bem.info/methodology/', 'сайт БЭМ, методологии веб-разработки.'),
('HTTP', 'https://httpwg.org/', 'документация HTTP.'),
('devdocs.io', 'https://devdocs.io/', 'документации к различным технологиям, собранные в одном месте.'),
('DummyJSON', 'https://dummyjson.com/', 'фейковые JSON в качестве плейсхолдеров для разработки и тестирования.'),
('Введение в Postman', 'https://habr.com/ru/companies/kolesa/articles/351250/', 'обзорная статья про Postman.'),
('json:api', 'https://jsonapi.org/', 'спецификация JSON.'),
('Что JavaScript-разработчику следует знать о Curl', 'https://habr.com/ru/articles/508592/', 'обзорная статья про Curl.'),
('OpenAPI Specification', 'https://spec.openapis.org/oas/latest.html', 'спецификация OpenAPI.');
INSERT INTO tags (tag, link_id) VALUES
('теги', id),
('compatibility', 1),
('web', 1),
('js', 2),
('lib', 2),
('studybook', 3),
('docs', 3),
('web', 3),
('html', 3),
('css', 3),
('js', 3),
('css', 4),
('html', 5),
('cheatsheet', 5),
('docs', 6),
('web', 6),
('html', 6),
('css', 6),
('js', 6),
('css', 7),
('article', 7),
('tool', 8),
('html', 8),
('studybook', 9),
('js', 9),
('tool', 10),
('design', 10),
('design', 11),
('cheatsheet', 12),
('maths', 12),
('js', 12),
('html', 12),
('css', 12),
('bash', 12),
('c', 12),
('c++', 12),
('c#', 12),
('clojure', 12),
('coffeescript', 12),
('dart', 12),
('elixir', 12),
('erlang', 12),
('kotlin', 12),
('php', 12),
('ruby', 12),
('rust', 12),
('typescript', 12),
('zig', 12),
('swift', 12),
('python', 12),
('java', 12),
('haskell', 12),
('go', 12),
('json', 12),
('markdown', 12),
('vim', 12),
('toml', 12),
('xml', 12),
('yaml', 12),
('design', 13),
('practice', 14),
('html', 14),
('css', 14),
('js', 14),
('community', 14),
('css', 15),
('practice', 15),
('cheatsheet', 16),
('algorithms', 16),
('optimization', 16),
('docs', 17),
('bash', 17),
('c', 17),
('c++', 17),
('clojure', 17),
('coffeescript', 17),
('css', 17),
('dart', 17),
('elixir', 17),
('erlang', 17),
('git', 17),
('html', 17),
('javascript', 17),
('kotlin', 17),
('php', 17),
('ruby', 17),
('rust', 17),
('typescript', 17),
('zig', 17),
('tool', 18),
('python', 18),
('js', 18),
('c', 18),
('c++', 18),
('java', 18),
('js', 19),
('example', 19),
('article', 20),
('optimization', 20),
('community', 21),
('practice', 21),
('js', 21),
('python', 21),
('c', 21),
('c++', 21),
('c#', 21),
('java', 21),
('php', 21),
('coffeescript', 21),
('typescript', 21),
('ruby', 21),
('haskell', 21),
('kotlin', 21),
('go', 21),
('elixir', 21),
('clojure', 21),
('dart', 21),
('erlang', 21),
('sql', 21),
('bash', 21),
('rust', 21),
('practice', 22),
('python', 22),
('c#', 22),
('c++', 22),
('java', 22),
('php', 22),
('typescript', 22),
('ruby', 22),
('haskell', 22),
('kotlin', 22),
('elixir', 22),
('clojure', 22),
('dart', 22),
('rust', 22),
('practice', 23),
('testing', 23),
('js', 23),
('html', 23),
('css', 23),
('python', 23),
('c', 23),
('c#', 23),
('c++', 23),
('java', 23),
('php', 23),
('typescript', 23),
('ruby', 23),
('kotlin', 23),
('go', 23),
('elixir', 23),
('erlang', 23),
('sql', 23),
('swift', 23),
('practice', 24),
('js', 24),
('python', 24),
('c', 24),
('c#', 24),
('c++', 24),
('java', 24),
('php', 24),
('typescript', 24),
('ruby', 24),
('kotlin', 24),
('go', 24),
('elixir', 24),
('dart', 24),
('erlang', 24),
('swift', 24),
('rust', 24),
('css', 25),
('docs', 25),
('community', 26),
('practice', 26),
('js', 26),
('typescript', 26),
('html', 26),
('css', 26),
('web', 27),
('js', 27),
('css', 27),
('html', 27),
('git', 28),
('js', 28),
('algorithms', 29),
('maths', 29),
('history', 29),
('hardware', 29),
('community', 30),
('community', 31),
('git', 32),
('java', 33),
('python', 33),
('css', 33),
('c#', 33),
('go', 33),
('ruby', 33),
('clojure', 33),
('js', 33),
('html', 33),
('php', 33),
('c', 33),
('typescript', 33),
('elixir', 33),
('studybook', 33),
('practice', 33),
('community', 34),
('php', 35),
('docs', 35),
('community', 36),
('js', 37),
('html', 37),
('lib', 37),
('studybook', 38),
('html', 38),
('css', 38),
('js', 38),
('php', 38),
('typescript', 38),
('python', 38),
('java', 38),
('c++', 38),
('rust', 38),
('sql', 38),
('git', 38),
('js', 39),
('lib', 39),
('coffeescript', 40),
('docs', 40),
('bash', 41),
('cheatsheet', 41),
('web', 42),
('js', 42),
('html', 42),
('css', 42),
('studybook', 43),
('html', 43),
('css', 43),
('js', 43),
('sql', 43),
('python', 43),
('java', 43),
('php', 43),
('c', 43),
('c++', 43),
('c#', 43),
('svg', 44),
('tool', 44),
('practice', 45),
('web', 46),
('tool', 46),
('design', 47),
('css', 48),
('css', 49),
('design', 49),
('css', 50),
('design', 50),
('css', 51),
('studybook', 51),
('article', 52),
('css', 52),
('css', 53),
('practice', 53),
('css', 54),
('design', 54),
('design', 55),
('js', 56),
('json', 57),
('jsx', 57),
('Java', 57),
('kotlin', 57),
('sql', 57),
('typescript', 57),
('toml', 57),
('yaml', 57),
('xml', 57),
('tool', 57),
('php', 58),
('article', 58),
('python', 59),
('article', 59),
('article', 60),
('ruby', 60),
('article', 61),
('security', 61),
('web', 62),
('article', 62),
('web', 63),
('article', 63),
('vim', 64),
('cheatsheet', 64),
('article', 65),
('hardware', 65),
('cheatsheet', 66),
('algorithms', 66),
('algorithms', 67),
('studybook', 67),
('web', 68),
('article', 68),
('js', 69),
('docs', 69),
('maths', 70),
('book', 70),
('design', 71),
('article', 72),
('article', 73),
('algorithms', 73),
('testing', 74),
('tool', 74),
('algorithms', 75),
('algorithms', 76),
('article', 76),
('article', 77),
('algorithms', 77),
('web', 78),
('docs', 78),
('web', 79),
('docs', 79),
('web', 80),
('docs', 80),
('css', 80),
('html', 80),
('js', 80),
('bash', 80),
('c', 80),
('c++', 80),
('clojure', 80),
('coffeescript', 80),
('dart', 80),
('elixir', 80),
('erlang', 80),
('go', 80),
('haskell', 80),
('kotlin', 80),
('php', 80),
('python', 80),
('ruby', 80),
('rust', 80),
('typescript', 80),
('markdown', 80),
('json', 81),
('testing', 81),
('tool', 81),
('article', 82),
('testing', 82),
('json', 83),
('docs', 83),
('web', 84),
('bash', 84),
('web', 85);
('docs', 85);
